sonar.projectKey=apchavez_gcp-go
sonar.organization=apchavez
sonar.projectName=gcp-go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/*_test.go
